### ISSUE TITLE
[Feat] For문 파싱에 대한 테스트

### ISSUE THREAD

**Issue by ujkkk** [edu-pi/Backend-Code-Analysis-Server#15]
## 📝 Description
**무엇을?**
- For문 파싱에 대한 테스트

**왜?**
- 안정성 확보위해

## ❗️Todo
- [ ] 테스트 코드 작성 방법 공부
- [ ] 테스트 케이스 생각
- [ ] 테스트 코드 짜기

**Comment by ujkkk** [comment]
고민 : for문은 반복문이다 보니 검증해야될 데이터가 너무 길다.
파일로 따로 빼야하나?

**Comment by ujkkk** [comment]
우선 매번 콘솔에서 json 데이터 보기 불편해서 파일 생성하는 함수 만듦. 

```
def nodes_to_json(nodes):
    # Node 객체 리스트를 사전 목록으로 변환
    nodes_dict_list = [asdict(node) for node in nodes]

    # 사전 목록을 JSON 형식 문자열로 변환
    return json.dumps(nodes_dict_list, indent=4)


def write_nodes_to_file(vizs):
    with open('nodes.json', 'w') as f:
        f.write(vizs)


if __name__ == "__main__":
    vizs = nodes_to_json(main())
    write_nodes_to_file(vizs)
    print(vizs)
```


![image](https://github.com/Co-due/Code-Analysis-Server/assets/88374384/82ad9f1b-f926-4282-9a7c-c84b960bc39d)

**Comment by ujkkk** [comment]
오류 **AttributeError: 'list' object has no attribute 'target'**

```
self = <app.analysis.generator.for_generator.ForGenerator object at 0x1089cd210>
node = [<ast.For object at 0x1084f73a0>]
elem_manager = <MagicMock spec='CodeElementManager' id='4427494800'>

    def __init__(self, node: ast.For, elem_manager: CodeElementManager):
>       self.__target = node.target
E       AttributeError: 'list' object has no attribute 'target'

../../../app/analysis/generator/for_generator.py:11: AttributeError
```

원인 : node 객체가 ast.For 타입의 인스턴스가 아님. node를 넘길 때 body[0]으로 넘겨야 했는데 body를 넘겨서 리스트가 넘어감

**Comment by ujkkk** [comment]
### 문제
for i in range(1,a):
    pass 같이 변수가 들어가는 경우의 테스트를 못하겠음

**해결 방안** 
 a에 접근하기 위해서 Namepaser의 parse 함수를 호출하면 5를 리턴하도록 목업 함수를 지정함
`@pytest.mark.parametrize("node, expect", data__get_identifier())
def test___get_identifiers(for_generator, node, expect):
    # for i in range(3): 일 때 [3]을 반환하는지 확인

    generator = for_generator(node)
    with patch.object(NameParser, 'parse', return_value=5):
        actual = generator._ForGenerator__get_identifiers()

        assert actual == expect

### 발생 에러
```
          identifier_list.append(identifier.value)
E           AttributeError: 'int' object has no attribute 'value'에러 발생
```
**원인 : 값을 바로 리턴하는것이 아닌 ast.Name객체를 리턴해야 했음**
변경 전
```
    with patch.object(NameParser, 'parse', return_value=5):
        actual = generator._ForGenerator__get_identifiers()
```
변경 후
 ```
   with patch.object(NameParser, 'parse', return_value=ast.Name(id='a', value=5, expressions=['a', '5'])):
        actual = generator._ForGenerator__get_identifiers()
```

**Comment by ujkkk** [comment]
json 데이터를 따로 함수로 뺄 때 null 값이 있는데 파이썬에서 null을 인식못해서 에러남

<img width="395" alt="image" src="https://github.com/Co-due/Code-Analysis-Server/assets/88374384/b109641e-89ba-494a-8538-8981e2424728">
