### ISSUE TITLE
[Feat] ast.brake 구현

### ISSUE THREAD

**Issue by ujkkk** [edu-pi/Backend-Code-Analysis-Server#151]
## 📝 Description
**무엇을?**
- ast.brake 시각화 지원

**왜?**
- 사용자가 break도 시각화하여 볼 수 있기 위함

## ❗️Todo
- [x] generator를 위한 분석 객체 BreakStmtObj 만들기
- [x] flowContorolViz에 break 추가
- [x] Generator에서 반복문(for)에 break 나올 경우의 로직 추가

## ETC
기타사항

**Comment by ujkkk** [comment]
**generator를 위한 분석 객체 BreakStmtObj 만들기**

```
@dataclass(frozen=True)
class BreakStmtObj:
    id: int
    expr: str
    type: str = field(default="flowControl", init=False)
```

예시
```
BreakStmtObj(id=1, expr="break", type="flowControl")
```

**Comment by ujkkk** [comment]
**flowContorolViz에 break 추가**

예시
```
FlowControlViz(id=3, depth=2, expr='break', highlights=[0, 1, 2, 3, 4], type='flowControl'),
```

**Comment by ujkkk** [comment]
break는 while문이나 For문의 중간에 나올 수 있음

즉 For문 body 추출 로직에서 breaksttmtObj를 잡아야함
```
        for i in for_stmt_obj.iter_obj.value:
            # init value 값 변경
            elem_manager.set_element(for_stmt_obj.target_name, i)

            body_steps = []
            for body in node.body:
                body_steps.append(StmtTraveler.travel(body, elem_manager))

            body_objs.append(BodyObj(cur_value=i, body_steps=body_steps))
```

에시 코드가 아래와 같을 때
```
for i in range(3):
    if(i==0):
        print("스타")
        break
```

body_steps에는 ifStmtObj 가 들어있음. 이때 breakStmtObjs는 ifStmtObj의 body에 들어있음
![image](https://github.com/user-attachments/assets/ee9294df-3ce1-4671-bcf4-72d1ec9d077d)

ifStmtObj.body.body_steps에 있음
![image](https://github.com/user-attachments/assets/1c14a163-965b-4c6e-b22f-fee767a62f4b)


**여기서 breakStmtObj를 찾은 후 이후의 obj는 제외하고 body_steps에 추가해야 함. 그리고 다음 루프로 넘어가야함**
