### ISSUE TITLE
[Search] assgin 함수에 대한 분석, 정리 후 공유

### ISSUE THREAD

**Issue by SongGwanSeok** [edu-pi/Backend-Code-Analysis-Server#26]
## 📝 Description
**무엇을?**
- ast.assign 함수에 대한 분석, 정리 후 공유

**왜?**
- 문득 ast.assign 함수에 있는 속성인 targets가 왜 배열로 여러개 들어오는지 의문이 들었다.
- assign의 모든 경우의 수를 포괄해 해결해주는 함수를 만들고 싶기 때문

## ❗️Todo
- [x] targets 속성에 대한 정의
- [x] value 속성에 대한 정의
- [x] 각 속성에 들어갈 수 있는 예시 정리

## ETC
기타사항

**Comment by SongGwanSeok** [comment]
@ujkkk 
정리한 노션 링크  - [assign 함수의 속성과 경우의 수 정리](https://www.notion.so/ac856822aa3d4d36beceafb2b569f9bb)
