### ISSUE TITLE
[Refactor] assign 부분 파일 분리

### ISSUE THREAD

**Issue by SongGwanSeok** [edu-pi/Backend-Code-Analysis-Server#35]
## 📝 Description
**무엇을?**
- parser.py에 있는 assign 부분 assign.py로 나누기

**왜?**
- parser.py 파일 크기가 점점 커진다는 느낌이 들기 때문

## ❗️Todo
- [x] assign 부분을 정의하기
- [x] assign.py 파일 만들기
- [x] 옮기면서 생기는 오류 수정하기

## ETC
기타사항
