### ISSUE TITLE
[Feat] 백엔드 api 정의해서 프론트와 연결

### ISSUE THREAD

**Issue by SongGwanSeok** [edu-pi/Backend-Code-Analysis-Server#36]
## 📝 Description
**무엇을?**
- 백엔드 api 정의해서 프론트와 연결

**왜?**
- 실제 우리가 작성한 코드가 프론트에 적용되는 결과 확인

## ❗️Todo
- [x] 코드를 받아서 보내주는 데이터 형식 정리하기
- [x] http 방식이나 데이터를 보내주는 방식 결정하기
- [x] 프론트 깃 레포지토리 clone해와 확인하기

## ETC
기타사항
