### ISSUE TITLE
[Feat] 기존 별찍기 코드 이외에 다양한 예시 정리 후 기능 구현

### ISSUE THREAD

**Issue by SongGwanSeok** [edu-pi/Backend-Code-Analysis-Server#37]
## 📝 Description
**무엇을?**
- 기존 별찍기 코드 이외에 다양한 예시 정리 후 공유

**왜?**
- 별찍기를 고민하면 다양한 예시가 나올 것으로 예상

## ❗️Todo
- [x] 별찍기 코드 다양한 예시 코드 정리
- [x] 정리한 예시 코드 공유
- [x] 예시별로 어떤 작업이 필요할 지 정리
- [x] 필요한 기능 구현

## ETC
기타사항

**Comment by SongGwanSeok** [comment]
다양한 별찍기 예시 

https://www.notion.so/e72cc99d0683468bbc1540b198c6d459
